# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: OWF Learn / MkDocs
pages:
- Home: index.md
- Overview: overview.md
- Install MkDocs: install.md
- New MkDocs Project: new-project.md
- Edit Content: edit.md
- Deploy Website: deploy.md
theme: readthedocs
repo_url:  https://github.com/OpenWaterFoundation/owf-learn-mkdocs
site_description:  Open Water Foundation Learn MkDocs
site_author:  Open Water Foundation
site_favicon:  OWF-Logo-Favicon-32x32.png
copyright:  Copyright Open Water Foundation
#extra_css:
#- css/extra.css
# Defaults to all JavaScript in the docs folder
# extra_javascript:
